Text-button/Dropdown
cornellh4i/ithaca-recovery pull request #48
Opened 2024-10-05 05:10 UTC by phoebe-qian

## Descriptions 
Allow user to create a new meeting by selecting meeting details (location, meeting type etc). Drop-down branch consists of code for the text-button AND drop-down because the dropdown functionality required the code for the text-button. 

Components are under the frontend/app/components/atoms folder. We have created sassy css files within the frontend/styles folder for both the textbox and drop-down to match the figma design. 

## Testing

Testing was done by adding these components onto the meetings/page.tsx page. 

Example of frontend components being used: 

Text Button Bare:
![image](https://github.com/user-attachments/assets/03d73382-a56e-4320-8400-7c4565c14fac)

Text Button when clicked:
![image](https://github.com/user-attachments/assets/96a2bef8-7b69-44a1-b1ff-c44b2db94c41)

Choosing drop downs: 
![image](https://github.com/user-attachments/assets/99968102-bb59-44a2-806c-4beaec4d52ae)

2024-10-14 01:56 UTC, owenchen04 commented on frontend/app/components/atoms/textbutton/index.tsx
> +  onClick: () => void;        // Function to call when button is clicked
when the button is pressed, we just want to call this `onClick` function and nothing else

2024-10-14 01:57 UTC, owenchen04 commented on frontend/app/meetings/page.tsx
please undo the changes in meetings/page.tsx

2024-10-14 01:59 UTC, owenchen04 commented on frontend/app/components/atoms/drop-down/index.tsx
> +const locations = [
these consts (locations, meetings, accounts) should be passed in as props to the dropdown component

2024-10-14 02:07 UTC, owenchen04 requested changes
Hi Phoebe and Alisha! Nice work so far on this ticket! Here are some high-level things to address:

- Please remove any of the `.json` or `yarn.lock` files from this commit
- Undo changes in `meetings/page.tsx`
- Remember that we are working with atomic design, so the textbutton and dropdown selector logic should not be connected at all at this point. In other words, the text button should be its own thing and should be able to be reused for any purpose (not just to trigger the dropdowns to be visible). While ultimately we'd like to put these components together into one "create meeting" organism, we're not quite there yet. When you click the text button, just have it call the onClick, which will eventually be passed in as a prop by whoever is using the button in a larger component. Similarly, the dropdown should be its own thing and shouldn't be connected to a text button at this point, nor should it have any references to the location, meetings, accounts, etc. Instead, try to create just a generic dropdown where the caller of the component can pass in their own options as a prop. This will allow us to reuse this single component for the location, Zoom acc, and group selectors, as opposed to hardcoding them within the component itself.

2024-10-24 23:05 UTC, phoebe-qian commented
All changes and suggestions should be reflected in the new pull request: Text-dropdown 2

2024-10-24 23:05 UTC, phoebe-qian commented
All changes and suggestions should be reflected in the new pull request: Text-dropdown 2

2024-10-24 23:05 UTC, closed without merging